# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 078be758f8e49ea4b05beb8bcef589a96e70fb264deb2ed4fdb537da27798a25c3fbc37002f875e2c9404f888bf5e5e7958e73fa4d7b0496d85c41aac614d9f1

test:
  secret_key_base: 0c121bd92439ab07ae5958cfa7e7ebac7d157ed14cb6c6035fca1a965c0ab9dda8a0724e857e5296d03c7f076ad1eaaa1b59739ad2ec5d873ba3fb5cc8cb5b10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
